Homebrew/actions

- README.md
update README to include `git-try-push` action description
> chore(docs): add git-try-push action description

- .github/workflows/brew-script.yml
- .github/workflows/cancel-previous-runs.yml
- .github/workflows/download-artifact-download.yml
- .github/workflows/download-artifact-upload.yml
- .github/workflows/git-try-push.yml
- .github/workflows/git-user-config.yml
No need to fire every workflow each time.
> workflows: only trigger if path changed

- README.md
Actions' descriptions are already provided in respective subdirectories. No need to repeat them.
> README: no need to repeat ourselves

- README.md
Add some information about development and structure of this repository.
cc @jonchang
> README: add development info

- .github/workflows/cancel-previous-runs.yml
- cancel-previous-runs/README.md
- cancel-previous-runs/action.yml
- cancel-previous-runs/main.js
Repurpose existing non-used Action to sweep all queued or in progress workflow runs and cancel those previous and duplicated ones.
> cancel-previous-runs: repurpose

- .github/workflows/setup-homebrew.yml
- setup-homebrew/README.md
- setup-homebrew/action.yml
- setup-homebrew/main.js
- setup-homebrew/main.sh
- setup-homebrew/package.json
This PR adds an Action which sets up Homebrew on Ubuntu or macOS.
https://github.com/Homebrew/brew/issues/7805
> Add setup-homebrew Action

- setup-homebrew/main.sh
Continuation of https://github.com/Homebrew/actions/pull/27
@MikeMcQuaid Think it is all now.
> setup-homebrew: fixes

- label-pull-requests/README.md
- label-pull-requests/action.yml
- label-pull-requests/main.js
Not sure if this is necessary or even works
Related: Homebrew/homebrew-core#58903
> label-pull-requests: add `missing_content` regex

- .github/workflows/setup-homebrew.yml
- setup-homebrew/README.md
- setup-homebrew/main.sh
- Set `name` consistently with "Set up Git repository" and "Set up Ruby" strings used by GitHub
- Set an `id` for use when caching
- Provide instructions and tests for caching RubyGems.
> setup-homebrew: various tweaks.

- setup-homebrew/main.sh
Check if the directory exists and clone it if it does not and update it otherwise.
> setup-homebrew/main.sh: change test-bot tap strategy.

- setup-homebrew/main.sh
Otherwise the current directory doesn't exist: https://github.com/Homebrew/brew/pull/8221/checks?check_run_id=950080990#step:4:27
> setup-homebrew/main.sh: cd before rm GITHUB_WORKSPACE.

- setup-homebrew/main.sh
Otherwise this won't test the correct revision.
> setup-homebrew/main.sh: don't update-reset test-bot when testing.

- setup-homebrew/main.sh
Need even more for `brew tests` to not fail.
> setup-homebrew/main.sh: chmod even more directories.

- setup-homebrew/main.sh
This handles cases where the repository exists but the remote does not:
https://github.com/Homebrew/homebrew-test-bot/pull/466/checks?check_run_id=953803650#step:4:25
Also, ensure that we don't mark homebrew-core as unsupported on self-hosted runners.
> setup-homebrew/main.sh: always set remote URL.

- .github/workflows/setup-homebrew.yml
- setup-homebrew/README.md
This is the default branch now.
> Use actions/*@main.

- .github/dependabot.yml
https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
> Add automatic dependency updates

- .github/workflows/download-artifact-download.yml
- .github/workflows/download-artifact-upload.yml
Use workflow_run event trigger.
> workflows: better test download-artifact

- .github/workflows/brew-script.yml
- .github/workflows/cancel-previous-runs.yml
- .github/workflows/dismiss-approvals.yml
- .github/workflows/download-artifact-download.yml
- .github/workflows/download-artifact-upload.yml
- .github/workflows/git-try-push.yml
- .github/workflows/git-user-config.yml
- .github/workflows/label-pull-requests.yml
- .github/workflows/post-comment.yml
- .github/workflows/setup-homebrew.yml
- setup-homebrew/README.md
- add consistent spacing
- only use multiline `run` when necessary
- remove identical, implicit `name` usage
- use `actions/cache@v1` for compatibility
> Various cleanup

- label-pull-requests/main.js
This PR changes the Action's behavior to actually remove labels from PRs that no longer apply.
For example:
1. Contributor makes a bump PR for a formula
2. @BrewTestBot labels the PR with `deprecated license`
3. Contributor fixes the license
4. @BrewTestBot removes the label from PR
> label-pull-requests: label if match, unlabel if no match

- git-try-push/action.yml
- git-try-push/main.js
> git-try-push: add force option

- review-cask-pr/Dockerfile
- review-cask-pr/README.md
- review-cask-pr/action.yml
- review-cask-pr/entrypoint.sh
- review-cask-pr/git_diff_extensions.rb
- review-cask-pr/review.rb
Move from `homebrew-cask` to here. (https://github.com/Homebrew/homebrew-cask/pull/88597)
> Add `review-cask-pr` action.

- review-cask-pr/review.rb
Review comments are formatted as markdown.
> Use markdown formatting for messages.

- review-cask-pr/review.rb
> Remove debug output.

- .github/workflows/post-review.yml
- post-review/README.md
- post-review/action.yml
- post-review/main.js
- post-review/package.json
Action for creating pull request reviews.
> Add `post-review` action.

- setup-homebrew/main.sh
> Fix cask repository regex.

- review-cask-pr/review.rb
Match both single and double quotes.
> Fix cask version regex to include double quotes.

- review-cask-pr/review.rb
Allow re-approving a pull request if there aren't yet any other reviews.
> Ignore labels and allow re-approving PRs.

- review-cask-pr/review.rb
> Fix `non_dismissed_reviews`.

- review-cask-pr/README.md
- review-cask-pr/review.rb
Allow passing pull request URL to test locally.
> Add support for debugging `review-cask-pr` locally.

- review-cask-pr/review.rb
As discussed here: https://github.com/Homebrew/homebrew-cask/pull/88947#issuecomment-690351576
cc @Homebrew/cask
> Automatically approve version reversals by members.

- review-cask-pr/review.rb
Better messaging for cases like these: https://github.com/Homebrew/homebrew-cask/pull/89208
> Comment if the same version bump was already merged.

- setup-homebrew/main.sh
This should avoid the flakiness we've been seeing (and match what GitHub Actions does for its own `git` calls).
> setup-homebrew: retry Git network calls.

- .github/workflows/brew-script.yml
- .github/workflows/cancel-previous-runs.yml
- .github/workflows/dismiss-approvals.yml
- .github/workflows/download-artifact-upload.yml
- .github/workflows/git-try-push.yml
- .github/workflows/git-user-config.yml
- .github/workflows/label-pull-requests.yml
- .github/workflows/post-review.yml
- .github/workflows/setup-homebrew.yml
Using actions/checkout with pull_request_target results in wrong ref (master) being checked out when PR is opened.
> workflows: use pull_request event trigger

- git-try-push/main.js
https://github.com/Homebrew/homebrew-core/runs/1237640124?check_suite_focus=true
cc @jonchang
> git-try-push: exit from loop after successful pull

- setup-homebrew/main.sh
Another take on:
https://github.com/Homebrew/actions/pull/115
cc @Rylan12
> setup-homebrew: checkout to repo default branch

- git-try-push/main.js
Failed workflow run: https://github.com/Homebrew/linuxbrew-core/runs/1280936989?check_suite_focus=true
> git-try-push: use only /usr/bin/git

- review-cask-pr/git_diff_extensions.rb
Fixes failure in https://github.com/Homebrew/homebrew-cask/pull/94881/checks?check_run_id=1516243752.
> Fix review for new versions with more parts than old.

- review-cask-pr/review.rb
These should be reviewed manually.
> Don't approve if version format changed.

- review-cask-pr/review.rb
Fix wrongful approval of https://github.com/Homebrew/homebrew-cask/pull/95284.
> Don't ignore version decrease for members.

- remove-disabled-formulae/action.yml
https://github.com/Homebrew/brew/issues/10786
> remove-disabled-formulae: delete unneeded env vars

- .github/workflows/brew-script.yml
- brew-script/README.md
- brew-script/action.yml
https://github.com/Homebrew/brew/issues/10786
> brew-script: delete unneeded env vars

- .github/workflows/test-create-gcloud-instance.yml
- create-gcloud-instance/config_runner.sh
- create-gcloud-instance/install_runner.sh
- create-gcloud-instance/start_runner.sh
These scripts are needed to setup the self hosted runners
> create-gcloud-instance (pre-requisite)

- .github/workflows/test-wait-for-idle-runner.yml
- wait-for-idle-runner/Readme.md
- wait-for-idle-runner/action.yml
- wait-for-idle-runner/main.js
- wait-for-idle-runner/package.json
This new actions is needed for https://github.com/Homebrew/homebrew-core/pull/75951
> wait-for-idle-runner (new action)

- wait-for-idle-runner/README.md
- wait-for-idle-runner/action.yml
- wait-for-idle-runner/main.js
2021-05-17T13:41:19.0375029Z internal/modules/cjs/loader.js:800
2021-05-17T13:41:19.0375807Z     throw err;
2021-05-17T13:41:19.0376412Z     ^
2021-05-17T13:41:19.0376787Z
2021-05-17T13:41:19.0378996Z Error: Cannot find module '@octokit/action'
2021-05-17T13:41:19.0379729Z Require stack:
2021-05-17T13:41:19.0380996Z - /home/runner/work/_actions/Homebrew/actions/master/wait-for-idle-runner/main.js
2021-05-17T13:41:19.0382495Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
2021-05-17T13:41:19.0383670Z     at Function.Module._load (internal/modules/cjs/loader.js:690:27)
2021-05-17T13:41:19.0384885Z     at Module.require (internal/modules/cjs/loader.js:852:19)
2021-05-17T13:41:19.0385861Z     at require (internal/modules/cjs/helpers.js:74:18) …
> wait-for-idle-runner: improvements

- create-gcloud-instance/README.md
- create-gcloud-instance/Readme.md
- create-gcloud-instance/action.yaml
- create-gcloud-instance/create-gcloud-instance.sh
- create-gcloud-instance/setup.sh
Needed by https://github.com/Homebrew/homebrew-core/pull/75951
> create-gcloud-instance (new action)

- create-gcloud-instance/action.yaml
Fixes:
action.yaml (Line: 35, Col: 7): Required property is missing: shell
> create-gcloud-instance: set shell

- setup-homebrew/main.sh
Provide temporary migration path from `GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED`.
> Use `GITHUB_ACTIONS_HOMEBREW_MACOS_SELF_HOSTED` variable

- setup-homebrew/main.sh
> setup-homebrew: fix GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED reference.

- .github/workflows/bump-formulae.yml
- bump-formulae/README.md
- bump-formulae/action.yml
- bump-formulae/main.rb
This PR adds a new action which serves takes output from `brew livecheck` and bumps selected formulae.
Based on my dawidd6/action-homebrew-bump-formula action.
> Add bump-formulae action

- label-pull-requests/action.yml
- label-pull-requests/main.js
Needed for https://github.com/Homebrew/homebrew-core/pull/84166
> label-pull-requests: support multiple *content constraints

- .github/workflows/vendor-node-modules.yml
Otherwise it'll error if there's nothing to commit.
> workflows/vendor-node-modules: commit only when necessary

- label-pull-requests/main.js
Closes: https://github.com/Homebrew/actions/issues/230
> label-pull-requests: do not label empty body PRs

- create-gcloud-instance/create-gcloud-instance.sh
This is an attempt to fix:
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
- The resource 'projects/ubuntu-os-cloud/zones/europe-west1-b/imageFamilyViews/ubuntu-2004-lts' was not found
> create-gcloud-instance: user newer image

- bump-formulae/action.yml
Create pull requests for outdated formulae.
> bump-formulae: open PRs

- create-gcloud-instance/create-gcloud-instance.sh
The previous image definition is broken
> create gcloud instance: use proper family

- create-gcloud-instance/create-gcloud-instance.sh
Needed by https://github.com/Homebrew/homebrew-core/pull/92991
> create-gcloud-instance: increase disk size

- label-pull-requests/main.js
continuing #257
relates to https://github.com/Homebrew/homebrew-core/pull/99475
> label-pull-requests: accept array of paths

- failures-summary-and-bottle-result/action.yml
> failures-summary: fix faulty `if`

- failures-summary-and-bottle-result/action.yml
> failures-summary: fix nonexistent variable

- .github/workflows/setup-homebrew.yml
Should remove this again once fixed.
> setup-homebrew: reenable ubuntu-latest.

- .github/workflows/brew-script.yml
- .github/workflows/bump-formulae.yml
- .github/workflows/check-commit-format.yml
- .github/workflows/dismiss-approvals.yml
- .github/workflows/git-try-push.yml
- .github/workflows/label-pull-requests.yml
- .github/workflows/post-comment.yml
- .github/workflows/post-review.yml
- .github/workflows/setup-commit-signing.yml
- review-cask-pr/Dockerfile
Permission fixes, PATH fixes and a move from Ubuntu 16.04 to 22.04.
Fork PRs are still not supported for some workflows.
> Fix CI failures

- git-try-push/action.yml
- git-try-push/main.js
Needed for Homebrew/homebrew-core#126776.
> Allow pushes with `--force`.

- .github/workflows/brew-script.yml
- .github/workflows/check-commit-format.yml
- .github/workflows/download-artifact-download.yml
- .github/workflows/download-artifact-upload.yml
- .github/workflows/label-pull-requests.yml
- .github/workflows/setup-homebrew.yml
- .github/workflows/vendor-node-modules.yml
These are all mostly adding quotes to variable expansions. The only one
that isn't is the replacement of `ls | awk` with a call to `stat` in
`setup-homebrew.yml`.
> workflows: fix actionlint errors

- create-gcloud-instance/create-gcloud-instance.sh
https://github.com/Homebrew/homebrew-core/actions/runs/4710794724/jobs/8357947099
Current zone does not seem to have enough resources for us.
> create-gcloud-instance: change zone

- bump-packages/README.md
- bump-packages/action.yml
This should allow autobumping casks.
> bump-packages: new action

- post-build/action.yml
This will allow us to replace these steps in `tests.yml` and
`dispatch-*.yml`.
> Add post-build action

- post-build/action.yml
Previously built bottles will be downloaded here after
Homebrew/homebrew-test-bot#922.
> post-build: remove `bottle-cache`

- count-bottles/action.yml
- count-bottles/count.sh
- post-build/action.yml
Needed for Homebrew/homebrew-test-bot#927.
> count-bottles, post-build: updates for dependent tests caching

- find-related-workflow-run-id/action.yml
Follow-up to Homebrew/homebrew-core@268191c0e25b0eecd99e963143df98f2005a1887.
> Add find-related-workflow-run-id action

- .github/dependabot.yml
The docs claim this does nothing on npm, but I want to see if that's still true.
> dependabot.yml: update all dependency types

- .github/workflows/bump-formulae.yml
- .github/workflows/download-artifact-download.yml
- .github/workflows/git-try-push.yml
* bump-formulae: use runner that has homebrew-core
* download-artifact (download): fix race condition when multiple PRs are run the upload part at once.
* git-try-push: fix race condition when multiple runs happen at once
> workflows: fix various CI

- cancel-previous-runs/action.yml
- check-commit-format/action.yml
- dismiss-approvals/action.yml
- download-artifact/action.yml
- git-try-push/action.yml
- git-user-config/action.yml
- label-pull-requests/action.yml
- post-comment/action.yml
- post-review/action.yml
- setup-homebrew/action.yml
- wait-for-idle-runner/action.yml
> feat: bump runtime to node 20

- post-build/action.yml
> Revert "Generate build provenance before upload."

- bump-packages/action.yml
Reverts Homebrew/actions#497
Should be ready now that we have https://github.com/Homebrew/brew/pull/16751.
> Revert "Revert "bump-packages: use `--no-fork` switch on our taps""

- setup-homebrew/main.sh
From discussion in https://github.com/Homebrew/homebrew-core/pull/166913
> setup-homebrew: make sure `--tags` are fetched

- pre-build/action.yml
Fixes https://github.com/Homebrew/homebrew-core/actions/runs/8861277502/job/24334093140#step:3:104
> pre-build: fix workflow errors

- pre-build/action.yml
> pre-build: fix workflow failures (again)

- pre-build/action.yml
Follow up to:
- Homebrew/ci-orchestrator#15
- Homebrew/brew#17222
> pre-build: use more specific bottle glob

- setup-homebrew/action.yml
- setup-homebrew/main.mjs
- setup-homebrew/main.sh
> Revert "setup-homebrew: add brew-gh-api-token setting"

- bump-formulae/action.yml
- bump-packages/action.yml
Store the formulae and casks in arrays to eliminate code injection through those inputs.
Also, update the descriptions to note that inputs should be space-separated.
> bump-packages: better handle action inputs

- create-pull-request/README.md
- create-pull-request/action.yml
- create-pull-request/main.mjs
- create-pull-request/main.test.mjs
A PR creation action that chews at the API limit less than `gh pr create`.
> create-pull-request: add action

- .github/workflows/create-gcloud-instance.yml
- .github/workflows/git-try-push.yml
- .github/workflows/git-user-config.yml
- .github/workflows/setup-commit-signing.yml
- .github/workflows/setup-homebrew.yml
- .github/workflows/test.yml
- .github/workflows/vendor-node-modules.yml
- .github/workflows/wait-for-idle-runner.yml
- post-build/action.yml
- pre-build/action.yml
This helps with transparency and they get updated by Dependabot.
> workflows & actions: use full versions

- .github/workflows/vendor-node-modules.yml
> ci: switch to SSH signing

- .github/workflows/vendor-node-modules.yml
> workflows/vendor-node-modules: fix signing key

- setup-homebrew/main.sh
Might help with https://github.com/Homebrew/brew/pull/19424
> setup-homebrew: fix permissions of actions directory

- .github/workflows/actionlint.yml
- pre-build/action.yml
- setup-homebrew/action.yml
- setup-homebrew/main.mjs
- setup-homebrew/main.sh
It was merged into Homebrew/brew.
See https://github.com/Homebrew/brew/pull/20762
> Remove Homebrew/homebrew-test-bot tap
