- .github/workflows/download-artifact-download.yml
- .github/workflows/git-ssh.yml
- download-artifact/main.js
By default, the rest.js API only returns 30 results. Using `await` pagination should let us find older workflow runs.
> download-artifact: paginate workflow response

- .github/workflows/download-artifact-upload.yml
Use upload-artifact v2
release note, https://github.com/actions/upload-artifact/releases/tag/v2
> - Port entire action to typescript from a runner plugin so it is easier to collaborate and accept contributions
> - Upload artifacts using a wildcard pattern
> - Fix for artifact uploads sometimes not working with containers
> - Upload an artifact without providing a name
> workflows: use actions/upload-artifact v2

- .github/workflows/label-pull-requests.yml
- label-pull-requests/README.md
- label-pull-requests/action.yml
- label-pull-requests/main.js
- label-pull-requests/package.json
Per discussion here: https://github.com/Homebrew/brew/issues/7805
This PR adds an Action which labels pull requests when specified criteria match.
It makes a lot of API calls right now, cause it needs to first fetch list of open PRs, then fetch a list of changed files for each of those PRs and then fetch every changed file's content. But this way it is very flexible.
I went for JSON format as a criteria definition, as it is the easiest to implement with NodeJS, but I'm open for suggestions.
Also embedding JSON document in YAML isn't very friendly and sane, I know. Initially I thought about making a _custom DSL_ a'la GitHub search, like: `label:new formula,status:added,path:Formula/.+`, but abandoned it, as it required more work and I wanted to have a _working idea_ faster.
> Add label-pull-requests Action

- label-pull-requests/main.js
This PR refactors the Action in a way: first fetch data from API, then process it.
Also, it creates a new condition for labelling. Only if every file matches, label is added to PR.
> label-pull-requests: refactor and match all files

- .github/workflows/setup-homebrew.yml
- setup-homebrew/README.md
- setup-homebrew/main.sh
This is a better test because:
- it runs `brew config` for us
- this is what we're expecting users to run
- this is/shortly will be what `brew tap-new` is doing
> workflows/setup-homebrew: run test-bot.

- setup-homebrew/main.sh
This otherwise causes a minor explosion: https://github.com/Homebrew/homebrew-test-bot/pull/462/checks?check_run_id=950055360#step:4:32
> setup-homebrew/main.sh: don't tap test-bot for own repo.

- setup-homebrew/main.sh
> setup-homebrew/main.sh: chown HOMEBREW_PREFIX.

- setup-homebrew/main.sh
We need all of those in the PATH to be not-group-writable.
> setup-homebrew/main.sh: chown more directories.

- setup-homebrew/main.sh
In this situation we're not running the GitHub Actions "Set up Git" step so this will behave incorrectly.
> setup-homebrew/main.sh: don't symlink workspace when self-hosted.

- setup-homebrew/main.sh
GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED is not necessarily defined.
> setup-homebrew/main.sh: handle unbound variable.

- setup-homebrew/main.sh
Remove it unconditionally but recreate on the self-hosted runner and symlink elsewhere.
> setup-homebrew/main.sh: handle homebrew-core workspace.

- .github/workflows/setup-homebrew.yml
- setup-homebrew/main.sh
This wasn't caught by CI so add a test to check these in future.
> setup-homebrew: fix Bash syntax error.

- setup-homebrew/README.md
- setup-homebrew/main.sh
- Remove mention of `actions/setup-ruby` and note that it and `actions/checkout` are unnecessary when using this action.
- Only run `brew update-reset` on Homebrew/brew or Homebrew/homebrew-core when necessary (to improve speed).
- Handle self-hosted workers on Homebrew/brew and refuse to use them on non-homebrew-core taps.
- Fetch and checkout the right version of a tested tap.
- Fix Homebrew/homebrew-test-bot configuration so it is not cloned unless necessary (and is when it is).
- Add more comments.
> setup-homebrew: more tweaks.

- setup-homebrew/main.sh
Otherwise if it didn't exist already it wouldn't be and we're not as consistent a `actions/checkout` replacement.
> setup-homebrew/main.sh: always symlink tap workspace.

- setup-homebrew/main.sh
Need to use `git remote add origin` in this case.
> setup-homebrew/main.sh: handle missing tap.

- setup-homebrew/main.sh
Otherwise this will always attempt to clone (causing failures on the Homebrew/homebrew-test-bot repository).
> setup-homebrew/main.sh: fix test-bot variable.

- git-try-push/main.js
This means that we can get updates without needing to manual run stash or having a clean tree.
> git-try-push: use `git pull --rebase --autostash`.

- setup-homebrew/main.sh
Allows running some scripts from the main `cask` tap on Linux in other `cask-*` taps.
> Tap `homebrew/cask` if not already installed.

- .github/workflows/label-pull-requests.yml
- label-pull-requests/README.md
- label-pull-requests/action.yml
- label-pull-requests/main.js
This allows us to run this Action on pull_request_target event, rather than on schedule, which reduces API calls count and is faster.
> label-pull-requests: support only pull_request* events

- git-try-push/main.js
- Don't try to force push with lease the first time as we may not have an up-to-date or existing branch which will cause a failure.
- Ensure that the sleep is always a non-zero value.
See: https://github.com/Homebrew/brew/runs/1064382305?check_suite_focus=true
> git-try-push: tweak force push and backoff behaviour.

- setup-homebrew/main.sh
Update all other installed official cask taps when setting up any cask tap since otherwise testing `conflicts_with` fails (see https://github.com/Homebrew/homebrew-cask/pull/88595).
> Update other official cask taps when in a cask tap.

- setup-homebrew/action.yml
- setup-homebrew/main.sh
Needed for debugging CI failures.
> Add `debug` input for `setup-homebrew`.

- review-cask-pr/git_diff_extensions.rb
- review-cask-pr/review.rb
This should handle cases such as https://github.com/Homebrew/homebrew-cask-versions/pull/9582.
cc @Homebrew/cask
> Improve detection of version increases by using the `before_comma` part.

- label-pull-requests/README.md
- label-pull-requests/action.yml
- label-pull-requests/main.js
This adds an `except` field to `label-pull-request` that allows files to be excluded by absolute path, i.e. without regex
Example:
```json
{
"label": "legacy",
"path": "Formula/.+@.+",
"except": [
"Formula/python@3.8",
"Formula/python@3.9"
]
}
```
Related: Homebrew/homebrew-core#61163
> label-pull-request: add `except`

- setup-homebrew/main.sh
Instead use `git_retry` consistently for `clone` and `fetch`es.
> setup-homebrew: don't use `brew tap` or `brew update-reset`.

- setup-homebrew/main.sh
https://github.com/Homebrew/actions/pull/94 broke CI for cask repos because while `brew tap` is idempotent, `git clone` isn't.
cc @MikeMcQuaid
> Only clone `homebrew/cask` if it doesn't exist.

- setup-homebrew/main.sh
Prevents errors such as in [this workflow run](https://github.com/dawidd6/homebrew-test-tap-new/runs/1198674370?check_suite_focus=true) from appearing.
```
brew pr-pull --debug --tap=$GITHUB_REPOSITORY $PULL_REQUEST
Error: undefined method `split' for nil:NilClass
Please report this issue:
https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:385:in `block in pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:378:in `each'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/dev-cmd/pr-pull.rb:378:in `pr_pull'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```
> setup-homebrew: always set origin HEAD

- setup-homebrew/main.sh
Alterate strategy from #98. Whenever we fetch something from a remote that's not HEAD (e.g. `git fetch origin $SHA`) also explicitly fetch HEAD.
> setup-homebrew: explicitly fetch upstream refs

- .github/workflows/cancel-previous-runs.yml
- cancel-previous-runs/README.md
- cancel-previous-runs/action.yml
- cancel-previous-runs/main.js
Should be merged in sync with: https://github.com/Homebrew/homebrew-core/pull/62127
Note that this isn't really tested, I still don't know how to fake trigger duplicate CI workflow run so we can see this Action, well... in action.
> cancel-previous-runs: repurpose to run on pull_request event

- setup-homebrew/main.sh
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Closes #101
> setup-homebrew: handle add-path deprecation

- cancel-previous-runs/main.js
We run this Action on pull_request_target event, no need to check workflow runs for e.g Homebrew:master branch.
I saw a situation where publishing jobs were cancelled because of it. This PR should solve the problem.
> cancel-previous-runs: query workflow runs only for pr branch and pull_request event

- setup-homebrew/main.sh
GitHub has requested we request our usage of shallow clones. As a result stop doing shallow clones of repositories.
> setup-homebrew: don't use shallow clones.

- setup-homebrew/main.sh
Allow `setup-homebrew` to be run on taps that don't use `master` as the main branch name.
GitHub has switched its default branch name to `main` so new taps that want to use the `setup-homebrew` action may use this as their main branch name. The action currently checks out the `master` branch by default, so this PR adds an optional setting for a different branch name (still defaults to `master`).
This is my first time diving into GitHub actions. What's the best way to test changes?
> Allow alternative branch names to setup-homebrew

- git-try-push/main.js
We're seeing a lot of issues on CI where bottles are getting correctly uploaded but the git info isn't getting merged into `master` due to transient git issues. This is because we're not doing retries of `git pull`s, just `git push`es. This pull request enables retry-and-backoff behavior on `git pull` as well.
https://github.com/Homebrew/homebrew-core/runs/1229540549?check_suite_focus=true
https://github.com/Homebrew/homebrew-core/runs/1228509044?check_suite_focus=true
https://github.com/Homebrew/homebrew-core/runs/1228508927?check_suite_focus=true
https://github.com/Homebrew/homebrew-core/runs/1228508997?check_suite_focus=true
> git-try-push: also retry pulls

- setup-homebrew/main.sh
Follow up to #104
As pointed out in https://github.com/Homebrew/actions/pull/104#issuecomment-706309912, the PR adding branch detection fails for non-core taps because it tried to reference the `DIR` variable which is never set.
I believe `DIR` should be changed to `HOMEBREW_TAP_REPOSITORY`.
Again, I'm not really sure how to go about testing this change.
CC: @miccal
> setup-homebrew: fix branch detection

- .github/workflows/check-commit-format.yml
- check-commit-format/README.md
- check-commit-format/action.yml
- check-commit-format/main.js
- check-commit-format/package.json
Checks that a pull request's commits follow our style. Uses the GitHub Statuses API to alert contributors and maintainers of a pull request's mergeability based on that.
https://github.com/Homebrew/homebrew-core/pull/61147 for an example (or this pull request)
> check-commit-format: new action

- .github/workflows/check-commit-format.yml
- check-commit-format/action.yml
- check-commit-format/main.js
Label pull requests instead of setting a failure status.
> check-commit-format: label pull requests

- .github/workflows/check-commit-format.yml
Following what the label-pull-requests workflow does.
> tests: unlabel after label succeeds

- README.md
Updates the README and adds info on how to start testing events locally. I figured most of this out by reading the source code for `@actions/core`, so hopefully this saves someone some time.
> README: add a bit more detail about local development

- setup-homebrew/main.sh
This commit breaks checking out pull request head on third-party taps.
Reverting it for now.
Example workflow run: https://github.com/dawidd6/homebrew-tap/pull/189/checks?check_run_id=1258197042
@Rylan12
> Revert "Allow alternative branch names to setup-homebrew"

- setup-homebrew/main.sh
This PR adds a small workaround to the `setup-homebrew` action to resolve an incompatibility between the `fontconfig` formula and the poppler installation in the GitHub Actions ubuntu images.
The workaround removes poppler's font artefacts in the `/usr/share/fonts/cmap` folder because the containing files will cause `fc-cache -frv`, the command used to refresh the font cache after installing `fontconfig`, to fail.
This workaround currently seems like the best option since poppler can also be installed using Homebrew, so the expected usage of Homebrew's `fontconfig` and the preinstalled poppler version are unlikely. Furthermore, ensuring that `fontconfig` can be installed can be crucial for many formula, as it is found in many dependency trees, including any dependency on `openjdk`.
This …
> setup-homebrew: add workaround to allow installation of fontconfig

- check-commit-format/main.js
- label-pull-requests/main.js
I have noticed an issue with our labelling workflow when creating PRs using [`gh`](https://github.com/cli/cli). If I create a PR and add a label using `gh`, the label isn't passed to GitHub actions with the `pull_request` event. This means that our labelling and commit-checking workflows think there are no labels on the PR. These workflows will then apply the changes it deems necessary which includes removing the label that I just added. An example of where this happened is in https://github.com/Homebrew/homebrew-core/pull/65712.
I reported this issue in the `gh` repo at https://github.com/cli/cli/issues/2489. I received a response saying that they were aware of the issue and that it was due to a limitation in the GitHub API. They are currently unable to add the labels in the request as …
> Fix gh PR labelling issue

- label-pull-requests/README.md
- label-pull-requests/main.js
Resolves #122
This adds a configuration option to the `label-pull-requests` workflow that allows for certain conditions to be marked with the `keep_if_no_match` setting. When set, `label-pull-requests` will not attempt to remove the label if it already exists and no longer matches. This will be used in homebrew/core by the `automerge-skip` label. Currently, the configuration for that label is this:
```json
{
"label": "automerge-skip",
"path": "Formula/(patchelf|binutils).rb"
}
```
This meant that when `label-pull-requests` was run, the `automerge-skip` label was removed for all PRs that didn't modify either `Formula/patchelf.rb` or `Formula/binutils.rb`. After this PR, I'll change the configuration to:
```json
{
"label": "automerge-skip",
"path": "Formula/(patchelf|binutils).rb", …
```
> label-pull-requests: add keep_if_no_match option

- remove-disabled-formulae/README.md
- remove-disabled-formulae/action.yml
- remove-disabled-formulae/main.rb
This PR adds a new action to detect outdated formulae and remove them.
See https://github.com/Homebrew/homebrew-core/pull/67386 and https://github.com/Homebrew/homebrew-core/issues/66360.
> Add remove-disabled-formulae action

- label-pull-requests/main.js
(I accidentally committed to master (https://github.com/Homebrew/actions/commit/2eb1605eab6c3d2aca7193642312f08b93f04884), which I then reverted (https://github.com/Homebrew/actions/commit/e9569ab1c3faf2e33f7f44b0168e59811f33ee81); now I'm opening a proper PR)
`keep_if_no_match` appears not to be working: https://github.com/Homebrew/homebrew-core/pull/67757
`constraint.wanted` is used to determine if a label should be kept and is `false` by default. This PR adds a line that sets `constraint.wanted` to `true` if the label exists and `keep_if_no_match` is enabled
> label-pull-requests: fix keep_if_no_match option

- label-pull-requests/main.js
PR #134 turned out not to have any effect, as the `automerge-skip` label is added and removed in the [`check-commit-format`](https://github.com/Homebrew/actions/blob/master/check-commit-format/main.js) action. ([`check-commit-format/action.yml`](https://github.com/Homebrew/actions/blob/master/check-commit-format/action.yml) defines `automerge-skip` as the default "failure label".)
This PR reverts #134, so that anyone reading the code does not become confused
Related:
- https://github.com/Homebrew/homebrew-core/pull/69992
- https://github.com/Homebrew/homebrew-core/pull/69994
- https://github.com/Homebrew/homebrew-core/pull/69996
- https://github.com/Homebrew/actions/pull/140
> Revert "label-pull-requests: fix keep_if_no_match option (#134)"

- review-cask-pr/review.rb
This PR updates the usage of Homebrew's GitHub API module as a consequence of Homebrew/brew#10626. Calls to the erstwhile `GitHub.open_api` (now a deprecated wrapper method) have been replaced with `GitHub::API.open_rest`.
> review-cask-pr/review.rb: update GitHub API usage

- setup-homebrew/main.sh
See the discussion here: https://github.com/Homebrew/actions/pull/148
In conclusion: this code is not used anymore nor is it tested on CI.
> setup-homebrew: remove Homebrew bootstrapping

- git-try-push/action.yml
- git-try-push/main.js
See Homebrew/brew#10856 and [this comment](https://github.com/Homebrew/brew/pull/10854#issuecomment-799414425) for context. This PR adds the ability to `git push --force-with-lease` on the first try, using a separate flag.
> git-try-push: add origin_branch option

- review-cask-pr/review.rb
Prevent things like https://github.com/Homebrew/homebrew-cask/pull/101292 from being approved.
> Don't allow interpolation in version.

- setup-homebrew/main.sh
By modifying permissions of some directories in Docker container we are able to run `brew` as `linuxbrew` user inside it without any friction (at least looking at `coreutils` testing PR).
> setup-homebrew: allow to run as normal user in container

- .github/workflows/setup-commit-signing.yml
- setup-commit-signing/README.md
- setup-commit-signing/action.yml
- setup-commit-signing/main.sh
This PR creates a new action to setup commit signing, to be used mainly with BrewTestBot. I thought creating a separate action would be useful in debugging issues with commit signing, and thus better than adding this to `git-user-config`.
Note: The test workflow I've added will not work unless the necessary secrets (`BREWTESTBOT_GPG_SIGNING_SUBKEY` and `BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE`) are accessible in this repository (cc @MikeMcQuaid).
Also, I was wondering if pushing a test signed commit to a branch to ensure that the "Verified" badge appears would be okay. Checking the output of `git log --show-signature -1` is not sufficient to ensure this (I noticed some issues when I was testing this functionality earlier).
> Create action to setup commit signing

- .github/workflows/setup-commit-signing.yml
- setup-commit-signing/main.sh
This PR removes the `--ignore-garbage` option which isn't available with `base64` on macOS runners. The workflow seems to work without using this option.
> setup-commit-signing: don't use `--ignore-garbage` with `base64`

- .github/workflows/setup-commit-signing.yml
- setup-commit-signing/README.md
- setup-commit-signing/main.sh
This fix is needed to prevent the GPG passphrase from being filtered out of the environment, causing `system "git", "commit" ...` to fail.
> setup-commit-signing: use HOMEBREW_GPG_PASSPHRASE

- .github/workflows/review-cask-pr.yml
- review-cask-pr/.rspec
- review-cask-pr/git_diff_extension.rb
- review-cask-pr/git_diff_extensions.rb
- review-cask-pr/review.rb
- review-cask-pr/spec/git_diff_extension_spec.rb
- review-cask-pr/spec/spec_helper.rb
Only allow decimal number changes (of any length) and hexadezimal changes (which match the length of the previous version).
> Make version format comparison check more strict.

- check-commit-format/main.js
Attempt to fix #168, don't set `is_success = false` when PR commit modifies a cask.
> check-commit-format: do not add `automerge-skip` to every Cask PR

- label-pull-requests/README.md
- label-pull-requests/action.yml
- label-pull-requests/main.js
Copy of #174 opened not from a fork
Adds a `pr_body_content` field that allows for a label to be applied using a regex match of the PR body.
This allows for https://github.com/Homebrew/homebrew-core/issues/76763 to be done.
I've tested this locally and it seems to work as expected. You can see the labels being automatically added and removed in https://github.com/Homebrew/homebrew-core/pull/76886
> label-pull-requests: add `pr_body_content` field

- wait-for-idle-runner/action.yml
This needs to be set in the workflow that uses this action.
Fixes:
Homebrew/actions/master/wait-for-idle-runner/action.yml (Line: 26, Col: 3): Unexpected value 'id'
> wait-for-idle-runner: remove id

- label-pull-requests/main.js
The triage workflow initially failed in Homebrew/homebrew-core#79146 because the PR body was empty. This PR aims to handle that case by setting `constraintApplies = true` if `body` is `null`.
> `label-pull-requests`: handle `null` PR body

- setup-homebrew/main.sh
> setup-homebrew: remove GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED workaround.

- setup-homebrew/main.sh
Look for another string, because the one already present... could not be present on self-hosted runners it turns out.
> setup-homebrew: check for another string in container too

- cancel-previous-runs/README.md
Replace with native GitHub Actions version.
> cancel-previous-runs: deprecated.

- setup-homebrew/main.sh
Fixes:
https://github.com/dawidd6/homebrew-tap/runs/3035160773?check_suite_focus=true
> setup-homebrew: link to workspace while not in container

- create-gcloud-instance/setup.sh
This breaks the setup in ubuntu 20.04, as the install script uses
fail checks to install the right libicu version, see:
https://github.com/fhammerl/runner/blob/53e76e0257007b065e6569a3b6ae82801d4b8c2f/src/Misc/layoutbin/installdependencies.sh#L77-L95
Our setup got broken by https://github.com/actions/runner/pull/1228.
The error message we had is:
Aug 10 17:15:43 linux-self-hosted-1 GCEMetadataScripts[1355]: 2021/08/10 17:15:43 GCEMetadataScripts: startup-script: ++ apt_get_with_fallbacks libicu72 libicu71 libicu70 libicu69 libicu68 libicu67 libicu66 libicu65 libicu63 libicu60 libicu57 libicu55 libicu52
Aug 10 17:15:43 linux-self-hosted-1 GCEMetadataScripts[1355]: 2021/08/10 17:15:43 GCEMetadataScripts: startup-script: ++ apt-get install -y libicu72
Aug 10 17:15:43 linux-self-hosted-1 …
> setup.sh: remove set -xeo pipefail

- create-gcloud-instance/setup.sh
Instead of removing completely the `pipefail` line for the whole script, do it only for the line which got broken by it.
> setup.sh: set and unset pipefail

- .github/workflows/vendor-node-modules.yml
> workflows/vendor-node-modules: use HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN

- .github/workflows/vendor-node-modules.yml
Only run when a specific label is added. Reduce permissions of `GITHUB_TOKEN`.
> workflows/vendor-node-modules: tighten security

- create-gcloud-instance/action.yaml
- create-gcloud-instance/create-gcloud-instance.sh
GitHub Actions now has its own `RUNNER_NAME` env. As a result we can no longer call our env by that name as it gets overridden, breaking the script.
> create-gcloud-instance: rename RUNNER_NAME env

- setup-homebrew/main.sh
It is very slow. If this ends up breaking something we should try think of an alternative.
> setup-homebrew: don't chmod /opt

- setup-homebrew/main.sh
(Re-)introduce `GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED` as we need to apply the self-hosted logic to Linux too.
> setup-homebrew: apply self-hosted logic to Linux

- create-gcloud-instance/config_runner.sh
Instead of setting it in workflows.
If this works, I will do the same for macOS in the next maintenance window (later this week probably).
> create-gcloud-instance: set Homebrew self-hosted env

- create-gcloud-instance/create-gcloud-instance.sh
Use the tagged version from canonical instead of the default versions from gcloud that disappear from time to time
> create gcloud instance: use tagged VM version

- .github/workflows/setup-commit-signing.yml
- setup-commit-signing/main.sh
This is useful when running in a Homebrew docker container, which won't have gnupg installed by default.
> setup-commit-signing: handle GPG versions < 2.1

- setup-commit-signing/main.sh
The home directory is for some reason not correctly cleared on self-hosted runners (this'll eventually be fixed by ephemeral). For security reasons, allow `GNUPGHOME` to be overridden.
> setup-commit-signing: allow prespecified GNUPGHOME

- setup-commit-signing/main.sh
brew env filters `GNUPGHOME`, so make sure it is set within the wrapper script instead of relying on the default.
> setup-commit-signing: set GNUPGHOME in wrapper script

- setup-homebrew/main.sh
Going to be using this in portable-ruby: https://github.com/Homebrew/homebrew-portable-ruby/pull/152
> setup-homebrew: support self-hosted in non-core taps

- remove-disabled-formulae/main.rb
Remove disabled formulae runs [have not been succeeding](https://github.com/Homebrew/homebrew-core/runs/6741661030?check_suite_focus=true#step:5:23) because `Formula::to_a` is no longer allowed (as of https://github.com/Homebrew/brew/pull/13347). This PR replaces `Formula::to_a` with `Formula::all` to solve the problem.
> Replace deprecated `Formula.to_a`

- create-gcloud-instance/config_runner.sh
Making use of a security feature released in 2.293.0 yesterday.
> create-gcloud-instance: require containers when using runner

- failures-summary-and-bottle-result/README.md
- failures-summary-and-bottle-result/action.yml
Based on the PR on Homebrew/homebrew-core#106155 the composite action will fail if we run it on Linux.
This is because the tests on Linux are using custom `workdir`. Thus, we need to somehow pass that directory to the composite action and make the tasks run in the appropriate directory. 
In this PR, I propose the approach to use `inputs`. Any feedback would be appreciated. Thank you.
> Update bottles failure and output composite action

- failures-summary-and-bottle-result/action.yml
This will prevent the summary from showing empty code blocks, such as in https://github.com/Homebrew/homebrew-core/actions/runs/2883783371/attempts/1#summary-7902798764.
> failures-summary: exit early if file is empty or nonexistent

- setup-homebrew/action.yml
- setup-homebrew/main.sh
fixes #236 
Allow passing the github api token (`GITHUB_TOKEN`) to authenticate with private repositories.
Example:
```yml
steps:
- name: Set up Homebrew
id: set-up-homebrew
uses: Homebrew/actions/setup-homebrew@master
with:
token: ${{ secrets.GITHUB_TOKEN }}
```
> setup-homebrew: private repositories support

- failures-summary-and-bottle-result/action.yml
It should be `</details>` and not `<\details>`.
> failure-summary: fix typo

- .github/workflows/setup-homebrew.yml
- setup-homebrew/main.sh
Should fix the problem introduced by https://github.com/actions/runner-images/issues/6283
> setup-homebrew: source homebrew from standard locations

- setup-homebrew/main.sh
Without this change the action exits with an error (e.g. `error: could not lock config file`) when running with a token using the _homebrew/ubuntu22.04:master_ image.
> setup-homebrew: git config after fixing permissions

- setup-homebrew/main.sh
Let's also add `sbin` to the `GITHUB_PATH` to stop complaints about it not being added e.g. https://github.com/Homebrew/brew/actions/runs/3429149696/jobs/5714410626#step:7:94
> setup-homebrew/main.sh: add sbin.

- create-gcloud-instance/create-gcloud-instance.sh
Since we use 22.04 everywhere else. Plus we need it for newer glib.
> create-gcloud-instance: use Ubuntu 22.04

- .github/workflows/cancel-previous-runs.yml
- create-gcloud-instance/setup.sh
Missed the permissions of `cancel-previous-runs`.
Fix style in `create-gcloud-instance`. I guess shellcheck updated at some point or something.
> More CI fixes

- .github/workflows/setup-commit-signing.yml
- .github/workflows/setup-homebrew.yml
- setup-homebrew/action.yml
- setup-homebrew/main.mjs
- setup-homebrew/main.sh
- setup-homebrew/post.mjs
- setup-homebrew/post.sh
Docker file ownership:
* Replace `chown` logic with `setfacl`.
- This allows the original permissions to not be disrupted, which the runner may need (and does for the new file commands).
* Increase to cover `RUNNER_TEMP`, including file commands (e.g. `GITHUB_OUTPUT`).
* Reset directories to original ACL/permissions after job completes.
Tokens:
* Adjust token behaviour to use HTTP headers rather than URL authentication.
- This matches how `actions/checkout` behaves.
* Cleanup token config after the job completes.
- This is a security enchancement.
* Document that tokens persist through job steps.
GitHub workspace:
* Remove `GITHUB_WORKSPACE` replacement for Homebrew/brew and Homebrew/homebrew-core.
- ⚠️ This is a breaking change affecting those repositories only.
* Adjust …
> Various improvements to setup-homebrew

- .github/workflows/setup-homebrew.yml
- setup-homebrew/main.sh
For CI outside of Homebrew/core, I've set cloning to be gated around `HOMEBREW_NO_INSTALL_FROM_API`. Core cloning is very slow so I'm trying to avoid there where possible.
> setup-homebrew: handle installs without Homebrew/core tapped

- setup-homebrew/main.sh
And mask it because it's a secret.
Fixes #330.
> setup-homebrew: fix token handling

- .github/workflows/vendor-node-modules.yml
- remove-disabled-formulae/main.rb
- review-cask-pr/review.rb
See here: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
TL;DR: The `set-output` command has been deprecated and we should be writing to the `$GITHUB_OUTPUT` environment file instead.
Old syntax:
```
- name: Set output
run: echo "::set-output name={name}::{value}"
```
New syntax:
```
- name: Set output
run: echo "{name}={value}" >> $GITHUB_OUTPUT
```
> Replace deprecated `set-output` command

- git-try-push/main.js
The pull-and-rebase step that this action does upon failure of the
initial `git push` (without force) destroys the changes we were trying
to force push in the first place.
Let's fix that by pushing with force right from the beginning. We've
already decided we're willing to destroy changes on the target branch,
so let's skip the initial `git push` which we already know is going to
fail.
See Homebrew/homebrew-core#126950 for additional context.
> git-try-push: skip initial push without force when `no_lease`

- label-pull-requests/main.js
Deleted files always match all `missing_content` constraints, adding superfluous labels.
> Don't count deleted files for `missing_content` constraint.

- check-commit-format/main.js
We're no longer squashing commits by default, so let's update this
action to handle that accordingly.
> check-commit-format: remove reference to autosquash

- git-try-push/main.js
When we pass `false` to `force` and `no_lease`, it is cast as a
`String`. Unfortunately, the string `'false'` is truth-y, so we've been
pushing with `--force` since we started using these inputs.
Let's fix that by making sure we interpret string arguments as intended.
> git-try-push: fix truth-y string arguments

- .github/workflows/setup-homebrew.yml
- setup-homebrew/main.sh
- setup-homebrew/post.sh
Also, run `shellcheck` in the test to avoid further errors.
> setup-homebrew: fix shellcheck errors

- setup-homebrew/action.yml
This makes the action run in debug mode if the runner is set to run in
debug mode.
See https://github.com/actions/github-script/blob/060d68304cc19ea84d828af10e34b9c6ca7bdb31/action.yml#L17
> setup-homebrew: default `debug` to current runner debug state

- .github/workflows/count-bottles.yml
- count-bottles/action.yml
- count-bottles/count.sh
This will allow us to replace a step in `tests.yml` and `dispatch-*.yml`
in Homebrew/homebrew-core.
> Add an action to count bottles

- failures-summary-and-bottle-result/action.yml
This is `${{ env.BOTTLES_DIR }}` everywhere we use it in Homebrew/core,
so let's make that the default here so we can skip having to specify it
at all.
> failures-summary-and-bottle-result: change default workdir

- count-bottles/action.yml
This should fix the error seen in https://github.com/Homebrew/homebrew-core/actions/runs/4796638560/jobs/8532735898.
Cc @carlocab
> count-bottles: fix "command not found" error

- git-try-push/action.yml
- git-try-push/main.js
The Sorbet and SPDX workflows use `origin_branch` as the branch to
rebase on but not push to. Let's restore that behaviour, but specify an
additional input, `remote_branch`, which specifies the remote branch
name to push to. This input will be needed in Homebrew/core.
While we're here, let's reduce the default number of tries so that the
workflow gives up after about 20 minutes instead of after almost an
hour.
- git-try-push: fix Sorbet and SPDX workflows in Homebrew/brew
- git-try-push: reduce default number of tries
> git-try-push: fix Sorbet and SPDX workflows in Homebrew/brew

- check-commit-format/action.yml
- check-commit-format/main.js
This adds the `autosquash` label to PRs that used to automatically be
autosquashed.
Also, while we're here, let's set a failing commit status for:
1. PRs with merge commits
2. PRs with commits that modify multiple formulae
Autosquash never handled PRs with these before, and maintainers end up
either having to ask users to fix their branch or fixing it up
themselves. Let's try to avoid that by nudging the user to fix it.
> check-commit-format: add autosquash label when needed

- post-build/action.yml
This is needed for use in the dependents step.
> post-build: add option to skip bottle upload

- check-commit-format/action.yml
- check-commit-format/main.js
This will prevent `automerge-skip` or `autosquash` labels from being
applied after the bottle commit has been pushed.
> check-commit-format: skip labelling PRs labelled `CI-published-bottle-commits`

- remove-disabled-formulae/main.rb
This is needed by the changes in Homebrew/homebrew-core#129852.
> remove-disabled-formulae: unconditionally write to `GITHUB_OUTPUT`

- post-build/action.yml
`--only-cleanup-after` wipes our shell, which causes succeeding commands
to fail.
> post-build: fix `Killed: 9` errors

- pre-build/action.yml
This is similar to #361, except for the steps before we call
`brew test-bot --only-formulae[-dependents]`.
> Add pre-build action

- setup-homebrew/main.sh
Just like how `brew update` is able to work if the Ruby side is completely broken, `setup-homebrew` should work similarly to get a functional version.
https://github.com/Homebrew/homebrew-core/actions/runs/4920922528/jobs/8790636214#step:2:37
(in this case, the bad version was from a Homebrew/brew CI run - not something that was merged)
In the longer term, we should perhaps implement `brew --repo <tap>` in shell.
> setup-homebrew: remove reliance on a functional brew Ruby

- gh-try-download/action.yml
This will allow us to try `gh run download` multiple times before giving
up, and will help fix some of the automerge workflow errors we have in
Homebrew/core.
> Add gh-try-download action

- pre-build/action.yml
- setup-homebrew/main.sh
This makes the `runner.debug` setting also make `brew` produce
verbose/debug output (unless the debug input is overridden).
> setup-homebrew: propagate `debug` to `brew`

- pre-build/action.yml
`brew test-bot --only-setup` can take a really long time, particularly
on GitHub macOS runners. Let's try to speed this up by caching our
Bundler Gems.
> pre-build: cache bundler gems

- pre-build/action.yml
PR branches have isolated caches, so storing a cache for a PR branch
isn't very useful.
We can generate a cache on `master` first and then restore from that
cache.
> pre-build: use only `actions/cache/restore`

- setup-homebrew/main.sh
Instead of only in homebrew-cask* CI.
Seems like the right thing to do if it isn't too much slower.
> setup-homebrew: always update cask repos

- setup-homebrew/action.yml
- setup-homebrew/main.mjs
- setup-homebrew/main.sh
Idea is this could make the `formulae.brew.sh` workflow a little more reliable by making the homebrew-core update job opt-out of updating the homebrew-cask tap (`cask: false`) and vice versa for the homebrew-cask update job.
Default behaviour continues to be to update both, since that's the safest and most reasonable thing to do.
> setup-homebrew: add ability to opt-out of tap updates

- setup-homebrew/main.sh
Edge case I missed because the conditions that invoke `else` changed.
> setup-homebrew: fix HOMEBREW_NO_INSTALL_FROM_API case

- .github/workflows/actionlint.yml
- pre-build/action.yml
- setup-homebrew/action.yml
- setup-homebrew/main.sh
- don't update core/cask/test-bot by default
- unset HOMEBREW_NO_INSTALL_FROM_API (which GitHub Actions sets by default
- use `brew update` to download formula/cask files
---
If this is ✅: we'll need to audit our usage of this action to ensure they are configured correctly to allow this change but it should reduce load on GitHub, failures seen by us and our users and better test the default Homebrew setup.
> setup-homebrew: update tweaks.

- setup-homebrew/main.sh
This should avoid repeatedly updating the same taps e.g. https://github.com/Homebrew/brew/pull/15634#issuecomment-1623885350
> setup-homebrew/main.sh: unset some env vars before `brew update`.

- setup-homebrew/main.sh
* Move autoupdate earlier just to make sure we don't undo what we do for third-party taps
* Unset `HOMEBREW_BOOTSNAP` so we don't install bundler gems here before any caching can kick in
> setup-homebrew: move autoupdate, unset bootsnap

- setup-homebrew/main.sh
* Allow `HOMEBREW_NO_INSTALL_FROM_API` for homebrew-core.
* Set `HOMEBREW_UPDATE_SKIP_BREW` which I'll use in brew to skip updating brew since we already do it here.
> setup-homebrew: fixes for brew and homebrew-core

- setup-homebrew/main.sh
Otherwise you have a chicken and egg problem where generating formulae.brew.sh requires a working formulae.brew.sh.
Usually is fine but in the event formulae.brew.sh has issues then it shouldn't prevent us from deploying.
> setup-homebrew: skip autoupdate for formulae.brew.sh CI

- setup-homebrew/main.sh
Turns some of https://github.com/Homebrew/actions/pull/398 into a Bash comment so it's more obvious when reading the code.
> setup-homebrew/main.sh: explain formula.brew.sh opt-out.

- setup-homebrew/main.sh
We're seeing `brew update` failures in multiple CI jobs. Hopefully
retrying it will make this more reliable.
> setup-homebrew: wrap `brew update` in retry logic

- setup-homebrew/main.sh
This existing one was just doing `brew update`.
> setup-homebrew/main: use correct auto-update flag.

- setup-homebrew/main.sh
These are better handled in `brew.sh` now and the names have changed.
> setup-homebrew/main: remove unnecessary unset variables.

- failures-summary-and-bottle-result/action.yml
- pre-build/action.yml
Strip colour codes from the output so GitHub Actions presents them more nicely in summaries.
> */action.yml: fix colour output.

- review-cask-pr/review.rb
This will be required after https://github.com/Homebrew/brew/pull/15940 is merged.
> review_cask_pr/review: use utils/curl.

- check-commit-format/main.js
Contributors do not generally seem to understand the implication of the `autosquash` label, and we often need to ask them to squash the commits, do the work for them, or let the PR be replaced (which is less ideal as it requires another full round of CI run). Let's instead fail this check and make the status check message more explicit, hoping this will draw more attention.
> check-commit-format: fail the status check when autosquash is needed

- pre-build/action.yml
`brew test-bot --only-setup` does this for us, and passes in the correct `--add-groups` flags. Let's not copy-paste it here for no benefit.
> pre-build: remove unnecessary extra gem install

- setup-homebrew/action.yml
This is breaking portable Ruby CI and is blocking me from making any progress on Ruby 3 - and I would like to do so this weekend.
The problem is Node 20 binaries shipped with the runner only work on macOS 10.15 and later and our 10.11-cross image runs 10.13 (the minimum requirement for Node 16).
We'll likely need to do any one of the following:
* Move 10.11-cross to be a 10.15 image (or later) with the 10.11 SDK. While I cannot yet guarantee this works, I haven't tried it yet so it might well work fine. Depends on compiler compatibility.
* Build our own Node, save it to the 10.11-cross image and use that instead of the prebuilt GitHub uses.
* Drop support for 10.11-10.14 entirely (or potentially less if we want a, e.g., 10.14-cross on 10.15). This will require a minor version bump of …
> setup-homebrew: temporarily revert to node 16

- setup-homebrew/main.sh
Mitigation for GitHub networking issues
`git remote set-head` documentation states:
> With `-a` or `--auto`, **the remote is queried** to determine its `HEAD`, then [...]
This is a network request that could fail if there are networking issues so wrap it in a retry too.
> setup-homebrew: retry `git remote set-head` calls

- setup-homebrew/main.sh
Fixes https://github.com/Homebrew/homebrew-test-bot/pull/975#issuecomment-1762500482
> setup-homebrew: don't reset test-bot to master in test-bot repo

- setup-homebrew/main.sh
The GNU coreutils base64 command will wrap long tokens to 74-character lines, breaking the Authorization header. Disable line wrapping on Linux.
This fixes #457.
> Disable base64 line wrapping on Linux.

- .github/workflows/setup-commit-signing.yml
It doesn't have the necessary secrets set so will always fail.
> workflows/setup-commit-signing: exclude dependabot.

- post-build/action.yml
Not only is it a bad idea, it's actively breaking things as `@main` currently points to the soon-to-be-released-but-isn't-quite-yet v4 release which contains significant changes that will require multiple adjustments to various parts of our CI. Even if v4 is released this month I reckon it will be next year before we can get aound to dealing with it.
> post-build: don't use `@main`

- post-build/action.yml
This PR adds a step in the `post-build` action that generates build providence for bottles that are built and will be uploaded. This is part of the larger effort to add verifiable build provenance for Homebrew bottles.
This is currently a draft and needs some further testing. Any feedback in the meantime is encouraged! Please let me know if there is a problem with signing post-build and before upload, or if there is a better place for this. My work so far leads me to believe this is the simplest place, but I'm certain others have more context that I am lacking.
> Generate build provenance before upload.

- label-pull-requests/README.md
- label-pull-requests/main.js
Not sure about naming.
Currently need a way to correctly label PRs when they modify more than one file (e.g. alias, multiple synced formulae, etc).
Particularly for some CI-impacting labels which can be problematic if missing, e.g. `long build` & `CI-build-dependents-from-source` for `ghc` always missing on next major/minor release.
> label-pull-requests: add `allow_any_match`

- count-bottles/action.yml
- failures-summary-and-bottle-result/action.yml
- post-build/action.yml
- pre-build/action.yml
- setup-homebrew/main.mjs
- setup-homebrew/post.mjs
When there is a broken `bash` in `PATH`, some actions may fail as in Homebrew/homebrew-core#162819. (See [this job](https://github.com/Homebrew/homebrew-core/actions/runs/7916916851/job/21612022470?pr=162819).) Let's modify those actions to use `/bin/bash` instead of an arbitrary `bash` from `PATH`; `brew` requires and always runs on `/bin/bash` anyway.
> actions: use `/bin/bash`

- count-bottles/count.sh
> count-bottles: use `/bin/bash`

- bump-packages/action.yml
This PR switches the behavior of the `bump-packages` Action to use the new `--no-fork` switch added in https://github.com/Homebrew/brew/pull/16740. As I called out in that PR:
>We can use this for BrewTestBot's autobump PR's. This will reduce the thousands of stale branches in the BrewTestBot forks (which I still plan to deal with).
Since the repo's branches get deleted after merging, this will save us the headache of cleaning up BrewTestBot's forks and allow us to see the branches more easily so they can be prioritized.
> bump-packages: use `--no-fork` switch on our taps

- bump-packages/action.yml
It helps to actually use the defined inputs.
Related to https://github.com/Homebrew/actions/pull/495.
> bump-packages: use `casks` intead of `cask`

- bump-packages/action.yml
This needs some changes on the `brew` side to handle this, so reverting until that can be addressed.
> Revert "bump-packages: use `--no-fork` switch on our taps"

- limit-pull-requests/README.md
- limit-pull-requests/action.yml
Resolves #337.
Sample usage:
```yaml
- uses: Homebrew/actions/limit-pull-requests@master
with:
except-users: |
BrewTestBot
except-author-associations: |
MEMBER
comment-limit: 10
comment: >
You already have 10 pull requests open. Please consider working on getting
the existing ones merged before opening new ones. Thanks!
close-limit: 50
close: true
```
An `except-author-associations` list is also accepted (e.g. `MEMBER`). We can discuss the exact rules when applying the action to the repos.
> limit-pull-requests: new action

- limit-pull-requests/action.yml
`gh pr list` does not list any PRs from users with a private profile (cli/cli#6879), so let's use another method to count PRs.
This allows us to have a limit higher than 99 too, though not quite necessary.
Before:
```console
$ gh pr list --state=open --author=BrewTestBot --json=number --jq=length --limit=100
23
```
After:
```console
$ gh api \
--method GET \
--header 'Accept: application/vnd.github+json' \
--header 'X-GitHub-Api-Version: 2022-11-28' \
--field state=open \
--paginate \
'/repos/Homebrew/homebrew-core/pulls' |
jq \
--raw-output \
--arg USER 'BrewTestBot' \
'map(select(.user.login == $USER)) | length'
23
```
> limit-pull-requests: do not use `gh pr list`

- limit-pull-requests/action.yml
Otherwise we'd see funny results.
See https://docs.github.com/en/actions/learn-github-actions/expressions#operators.
> limit-pull-requests: convert strings to numbers before comparing them

- limit-pull-requests/action.yml
By putting the comment body in an environment variable we can avoid having to escape quotes at all.
> limit-pull-requests: better handle quotes in comment body

- limit-pull-requests/README.md
- limit-pull-requests/action.yml
1. Avoid referencing inputs directly in shell scripts to prevent code injection.
2. Set `GH_REPO` to `${{ github.repository }}`. This is already set in [`triage.yml`](https://github.com/Homebrew/homebrew-core/blob/fd8564d9ba218798bf5dad00d47c5c4537ecb545/.github/workflows/triage.yml#L6) in `Homebrew/homebrew-core`, but if it's not and the repo is not checked out, `gh` will complain.
3. Update readme.
> limit-pull-requests: various improvements

- label-pull-requests/main.js
This might be reason for bug where `constraint.wanted == false` is removing the label even though there is a file that matches and `allow_any_match == true`
> label-pull-requests: `allow_any_match` only when adding label

- setup-homebrew/action.yml
- setup-homebrew/main.mjs
- setup-homebrew/main.sh
Want to add a job to `homebrew/core` to check tap_syntax on stable tag.
Currently, we need to manually keep track of this to avoid accidentally introducing errors to users on stable tags.
> setup-homebrew: support stable brew

- post-build/action.yml
- pre-build/action.yml
For the artifact actions we don't support v4 yet (#475), but there is now a v3-node20 we can use.
> pre/post-build: use Node 20 actions

- bump-packages/README.md
- bump-packages/action.yml
This PR allows anyone using `bump-packages` to specify if a fork should be used or not.
> bump-packages: add `fork` input

- post-build/action.yml
```
Error: Homebrew/actions/master/post-build/action.yml: (Line: 60, Col: 57, Idx: 1765) - (Line: 60, Col: 78, Idx: 1786): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load Homebrew/actions/master/post-build/action.yml
```
seen in https://github.com/Homebrew/homebrew-core/actions/runs/8577932249/job/23511213925?pr=168176
> post-build: use `GITHUB_ACTION_PATH` instead of `github.action_path`

- post-build/action.yml
- pre-build/action.yml
Companion to Homebrew/brew#17097.
Tested in ZhongRuoyu/homebrew-test#44.
Fixes #475.
> {pre,post}-build: use actions/{upload,download}-artifact@v4

- bump-formulae/README.md
- bump-packages/README.md
`|` preserves newlines, so the current usage tries to run `FORMULA-2` as a command.
Expected expand results:
```sh
brew bump --open-pr --formulae FORMULA-1 FORMULA-2 FORMULA-3
```
Actual results:
```sh
brew bump --open-pr --formulae FORMULA-1
FORMULA-2
FORMULA-3
```
This actual result is probably unexpected. So, I fix it to use `>` to fold newlines.
> Fix usage for `bump-{formulae,packages}`

- pre-build/action.yml
We currently download all previously built bottles, but that results in unnecessary downloads. Let's make the glob for downloading bottles more specific.
> pre-build: download only needed bottles

- .github/workflows/setup-homebrew.yml
- setup-homebrew/main.sh
* Don't assume `origin/HEAD` exists
* Don't checkout master first for stable - we don't support downgrades.
> setup-homebrew: handle stable on stable Docker images

- .github/workflows/setup-commit-signing.yml
Avoids the need to use a secret
> workflows/setup-commit-signing: generate testing key

- .github/workflows/git-try-push.yml
Avoids the need for a write token.
> workflows/git-try-push: use local directory

- remove-disabled-packages/README.md
- remove-disabled-packages/action.yml
- remove-disabled-packages/main.rb
This PR adds a modified version of the existing `remove-disabled-formulae` action that would work across both `homebrew-core` and `homebrew-cask`, and be useable in a repository that includes both Formula and Casks.
It may be worthwhile adding an additional feature to pass a variable for the amount of months a package should be disabled before being removed, as there may be a difference in process between `homebrew-core` and `homebrew-cask`.
> remove-disabled-packages: add action

- setup-homebrew/action.yml
- setup-homebrew/main.mjs
- setup-homebrew/main.sh
This should default to the current workflow runner's GITHUB_TOKEN, and should not need to be configured by the majority of users.
The primary purpose of this is to pre-configure
`HOMEBREW_GITHUB_API_TOKEN` so that attestations are verified in the CI.
> setup-homebrew: add brew-gh-api-token setting

- setup-homebrew/action.yml
- setup-homebrew/main.mjs
- setup-homebrew/main.sh
Turns out this wasn't the issue with https://github.com/Homebrew/.github/pull/140.
Reverts Homebrew/actions#559
> Revert "Revert "setup-homebrew: add brew-gh-api-token setting""

- .github/workflows/vendor-node-modules.yml
- brew-script/action.yml
- failures-summary-and-bottle-result/action.yml
- find-related-workflow-run-id/action.yml
- post-build/action.yml
- setup-commit-signing/action.yml
Avoid using inputs expanded with the `${{ .. }}` syntax in shell scripts to prevent code injection.
Also:
- `failures-summary-and-bottle-result`: make sure every `printf` gets a format string (`%s`) so that we don't get unexpected format sequences from the input.
- `post-build`: fix use of non-existent input `debug`.
> Handle input strings more robustly

- bump-packages/action.yml
Composite actions don't get the `INPUT_` variables automatically [^1].
[^1]: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
> bump-packages: fix input handling

- .github/workflows/vendor-node-modules.yml
This makes it no longer work for PRs from forks, but maintainers can still trigger it via `workflow_dispatch` after verifying the PR contents.
> workflows/vendor-node-modules: eliminate use of `pull_request_target`

- remove-disabled-packages/main.rb
This means the messaging in Homebrew/brew as-of https://github.com/Homebrew/brew/pull/17721 stays in sync with this action.
> remove-disabled-packages: use the limit set in Homebrew/brew.

- failures-summary-and-bottle-result/action.yml
`printf` only accepts `\n` in the format string (1st).
> failures-summary-and-bottle-result: fix formatting

- pre-build/action.yml
The new formula list is very noisy when the images haven't been updated in a while and is not useful information at all for Homebrew/core CI purposes.
> pre-build: set HOMEBREW_NO_UPDATE_REPORT_NEW

- api-commit-and-push/README.md
- api-commit-and-push/action.yml
- api-commit-and-push/main.mjs
- api-commit-and-push/main.test.mjs
- spec-helper.mjs
An action that take commits and pushes changes via the GitHub API rather than the git CLI.
Why? GitHub Apps need to use the API in order to sign commits. You cannot add a commit signing key to a GitHub app.
Using this also reduces the number of secrets required. Instead of a token + a GPG passphrase, you now only need a token.
See the README for example usage paired with `actions/create-github-app-token@v1`.
Will be used for https://github.com/Homebrew/brew/issues/17294.
> api-commit-and-push: add action

- create-pull-request/main.mjs
This will allow us to use cheaper calls directly with `gh api` instead
of `gh pr merge`.
> create-pull-request: output `node_id`

- create-pull-request/main.mjs
`core.getInput` returns an empty string if the value is not defined [^1]. Splitting an empty string in JavaScript returns an array with an empty string, which is truthy. That means the checks for labels and reviewers are always true, even if the input is not defined.
```node
> "".split("/")
[ '' ]
> Boolean([""])
true
```
In addition, add log output so that it's easier to figure out what's going on.
[^1]: https://github.com/actions/toolkit/blob/6dd369c0e648ed58d0ead326cf2426906ea86401/packages/core/src/core.ts#L120
> create-pull-request: fix empty string handling

- find-related-workflow-run-id/action.yml
- find-related-workflow-run-id/main.mjs
- find-related-workflow-run-id/main.test.mjs
> find-related-workflow-run-id: migrate to JS and add test

- find-related-workflow-run-id/action.yml
It turned out that `${{ }}` context access cannot be used here.
Fixes failure seen at https://github.com/Homebrew/homebrew-core/actions/runs/10973777949/job/30471527341.
> find-related-workflow-run-id: fix action definition

- create-or-update-issue/README.md
- create-or-update-issue/action.yml
- create-or-update-issue/main.mjs
- create-or-update-issue/main.test.mjs
Related: https://github.com/Homebrew/homebrew-core/pull/190657#issuecomment-2353378549
> create-or-update-issue: add action

- create-or-update-issue/README.md
- create-or-update-issue/main.mjs
- create-or-update-issue/main.test.mjs
- create-or-update-issue: add `close-comment` input
This allows posting a customised comment, like "The most recent deployment succeeded, closing issue", before closing an issue. This is used in formulae.brew.sh [^1].
- create-or-update-issue: add `close-from-author` input
This makes it possible to only check issues created by a specified user when searching for an existing issue. This is used in formulae.brew.sh [^2].
[^1]: https://github.com/Homebrew/formulae.brew.sh/blob/cc00b2d9476b85bba59c8469566774c496bbf381/.github/workflows/tests.yml#L272-L279
[^2]: https://github.com/Homebrew/formulae.brew.sh/blob/cc00b2d9476b85bba59c8469566774c496bbf381/.github/workflows/tests.yml#L257
> create-or-update-issue: add more inputs

- create-or-update-issue/README.md
- create-or-update-issue/action.yml
This was missed in ef36cd0 and 332f53a.
In addition, clarify usage in readme.
> create-or-update-issue: add missing inputs to action definition

- bump-packages/action.yml
This fixes the `fork` input so that the composite actions actually get the `INPUT_FORK` variable.
This was never passed correctly, meaning `brew bump --no-fork ...` is what always ran, even when `fork` was set to `true`.
> bump-packages: fix fork input handling

- .github/workflows/create-gcloud-instance.yml
- .github/workflows/git-try-push.yml
- .github/workflows/git-user-config.yml
- .github/workflows/setup-commit-signing.yml
- .github/workflows/test.yml
- .github/workflows/wait-for-idle-runner.yml
Trying again to fix these. I set `persist-credentials: true` for any jobs that had git operations, and `false` for the others. Let me know if I misunderstood.
> workflows: fix artipacked zizmor findings

- .github/workflows/git-user-config.yml
Avoid template injection by using environment variables to represent template values.
> workflows/git-user-config: fix template-injection zizmor findings

- remove-disabled-packages/main.rb
This changes the script to load the cask and formula files from the current tap rather than trying to load all installed taps.
> remove-disabled-packages: scope to current tap

- setup-homebrew/main.sh
relates to:
- https://github.com/Homebrew/homebrew-cask-fonts/pull/9413
- https://github.com/Homebrew/homebrew-cask-versions/pull/20219
> chore: remove `homebrew/homebrew-cask-fonts` and `homebrew/homebrew-cask-versions` repo refs

- .github/workflows/setup-commit-signing.yml
- .github/workflows/vendor-node-modules.yml
Now that we've removed all the GPG code, this is a no-op.
> workflows: remove no-op ssh signing value

- setup-homebrew/main.sh
This will fetch all branches which will allow for migration to the new `main` branch for self-hosted runners.
> setup-homebrew: set origin fetch and prune config.

- setup-homebrew/main.sh
To be merged when homebrew-core is using a default `main` branch.
See https://github.com/Homebrew/brew/issues/17296
> setup-homebrew: homebrew-core now uses `main`.

- setup-homebrew/main.sh
As first step to resolve #716 I replaced the `github.com` references which are probably pointing to the own tap repositories by this `$GITHUB_SERVER_URL`.
> Enable GHES support in `setup-homebrew`

- setup-homebrew/main.sh
We now use the `main` branch in Homebrew/core.
> setup-homebrew: set homebrew/core default branch to `main`

- setup-homebrew/main.sh
The `-c` flag should come before `init`.
> setup-homebrew: fix bad `git init` command

- pre-build/action.yml
Potential fix for [https://github.com/Homebrew/actions/security/code-scanning/49](https://github.com/Homebrew/actions/security/code-scanning/49)
To fix the problem, we should avoid using `${{ runner.os }}` directly in the shell script. Instead, we should set an environment variable (e.g., `RUNNER_OS`) to the value of `${{ runner.os }}` in the `env:` block of the step, and then reference it in the shell script using the native shell variable syntax (`$RUNNER_OS`). This change should be made in the step starting at line 65, specifically in the `if` statement on line 71. No additional imports or methods are needed; only the `env:` block and the shell script need to be updated.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
> Potential fix for code scanning alert no. 49: Code injection

- .github/workflows/create-gcloud-instance.yml
- .github/workflows/git-user-config.yml
- .github/workflows/setup-homebrew.yml
- .github/workflows/wait-for-idle-runner.yml
I noticed that we had a few of these workflows without `permissions: {}` left. 
Based on a cursory scan there should be no functional changes from dropping these permissions, since none of these workflows should require any permissions.
> ci: drop more workflow permissions
